"""Add campaign_ids to Company and Individual

Revision ID: b538e9bb3c7e
Revises: 
Create Date: 2026-05-28 17:36:41.245566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b538e9bb3c7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('campaign_ids', sqlite.JSON(), nullable=True))
    op.add_column('individuals', sa.Column('campaign_ids', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individuals', 'campaign_ids')
    op.drop_column('companies', 'campaign_ids')
    # ### end Alembic commands ###
